AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
  AppName:
    Type: String
  CallbackURL:
    Type: String
    Default: 'http://localhost'

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
          TemporaryPasswordValidityDays: 0
      UsernameAttributes:
        - email
      UserPoolName: !Sub ${Environment}-${AppName}-user-pool
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: family_name
          AttributeDataType: String
          Mutable: true
          Required: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      CallbackURLs:
        - !Sub ${CallbackURL}
      ClientName: !Sub ${Environment}-${AppName}-user-pool-client
      UserPoolId: !Ref UserPool
      SupportedIdentityProviders:
        - COGNITO

Outputs:
  UserPoolId:
    Value: !Ref UserPool